
codecov:
  token: ec5c1f2e-e2fe-4dff-bc7c-e112c17b268a

  bot: "codecov-io"
  ci:
    - "travis.org"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes

